sudo: false
cache:
  directories:
  - "$HOME/.gradle"
language: groovy
jdk:
- oraclejdk7
dist: precise
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: RB91TbokXRArer1GQD3AGfEWK/asNS0L/+d5NtQImik5dxQyj6purtg69Gi5MXOMgVJDlrv8IgxAQQyGKI96hvDZ5UpYPPYrod4lKcStLSwjihSualK8dNZ/4PAbNoGrszvWFJs5gzRYfkctpZ275CD/60F+IBOdYf0rgMQdnU0=
before_install:
- "./openssl-setup.sh"
matrix:
  fast_finish: true
script: "./travis-build.sh"
install: true
notifications:
  slack:
    secure: eSyvdf/vA0KGAyiITwe7ooD6BCX94PCy7o35HSkbfUbHB5XPJq/SkqRjjIeiwrgywVph+qGBPYmzIdep4BQwH+JFEfPu0gQoNWKeGAVmJ9LeFaP4vaXWvuRugunO9zUla4JT2cfmsxKVEoTfI1NIfT15hYBMHi+8CfgFlx2zOdk=
